from typing import Dict, List

THEMES: Dict[str, Dict] = {
    "default": {
        "name": "Default",
        "description": "Clean and modern with a pop of coral red",
        "preview_colors": ["#FFFFFF", "#333333", "#999999", "#FF6B6B"],
        "render_colors": {
            "bg": "#FFFFFF",
            "text": "#222222",
            "gradient_color": "#FFFFFF",
            "water": "#D6EAF8",
            "parks": "#D5F5E3",
            "road_motorway": "#FF6B6B",
            "road_primary": "#444444",
            "road_secondary": "#666666",
            "road_tertiary": "#888888",
            "road_residential": "#AAAAAA",
            "road_default": "#CCCCCC",
        },
    },
    "classic": {
        "name": "Classic",
        "description": "Warm beige tones with earthy accents",
        "preview_colors": ["#F5F5DC", "#2F2F2F", "#8B8B83", "#CD853F"],
        "render_colors": {
            "bg": "#F5F5DC",
            "text": "#2F2F2F",
            "gradient_color": "#F5F5DC",
            "water": "#C9DBD1",
            "parks": "#D4CDA8",
            "road_motorway": "#CD853F",
            "road_primary": "#3A3A3A",
            "road_secondary": "#5C5C54",
            "road_tertiary": "#7A7A72",
            "road_residential": "#9A9A92",
            "road_default": "#B0B0A8",
        },
    },
    "midnight": {
        "name": "Midnight",
        "description": "Deep dark blues for a nighttime feel",
        "preview_colors": ["#0D1117", "#1A1A2E", "#16213E", "#0F3460"],
        "render_colors": {
            "bg": "#0D1117",
            "text": "#C8D6E5",
            "gradient_color": "#0D1117",
            "water": "#0C1A30",
            "parks": "#0F1E18",
            "road_motorway": "#4A90D9",
            "road_primary": "#2E5090",
            "road_secondary": "#1E3A6E",
            "road_tertiary": "#1A2D55",
            "road_residential": "#15243F",
            "road_default": "#111C30",
        },
    },
    "ocean": {
        "name": "Ocean",
        "description": "Deep sea blues with teal highlights",
        "preview_colors": ["#001529", "#003566", "#006D77", "#83C5BE"],
        "render_colors": {
            "bg": "#001529",
            "text": "#B8D8E0",
            "gradient_color": "#001529",
            "water": "#001020",
            "parks": "#003030",
            "road_motorway": "#83C5BE",
            "road_primary": "#3FA5A0",
            "road_secondary": "#006D77",
            "road_tertiary": "#005566",
            "road_residential": "#003D50",
            "road_default": "#002A3A",
        },
    },
    "forest": {
        "name": "Forest",
        "description": "Rich greens inspired by dense woodlands",
        "preview_colors": ["#1A1C16", "#2D3A25", "#4A6741", "#8FBC8F"],
        "render_colors": {
            "bg": "#1A1C16",
            "text": "#C5D5B5",
            "gradient_color": "#1A1C16",
            "water": "#1A2530",
            "parks": "#1F2A18",
            "road_motorway": "#8FBC8F",
            "road_primary": "#5E8C5E",
            "road_secondary": "#4A6741",
            "road_tertiary": "#3A5231",
            "road_residential": "#2D3A25",
            "road_default": "#242E1E",
        },
    },
    "sunset": {
        "name": "Sunset",
        "description": "Warm oranges and yellows over a purple sky",
        "preview_colors": ["#1A0A2E", "#FF6B35", "#FF9F1C", "#FCE762"],
        "render_colors": {
            "bg": "#1A0A2E",
            "text": "#FFE0B2",
            "gradient_color": "#1A0A2E",
            "water": "#150830",
            "parks": "#2A1530",
            "road_motorway": "#FCE762",
            "road_primary": "#FF9F1C",
            "road_secondary": "#FF6B35",
            "road_tertiary": "#CC5530",
            "road_residential": "#8A3A25",
            "road_default": "#5A2535",
        },
    },
    "neon": {
        "name": "Neon",
        "description": "Electric neon colors on a dark background",
        "preview_colors": ["#0A0A0A", "#FF00FF", "#00FFFF", "#39FF14"],
        "render_colors": {
            "bg": "#0A0A0A",
            "text": "#EAEAEA",
            "gradient_color": "#0A0A0A",
            "water": "#001A1A",
            "parks": "#0A1A0A",
            "road_motorway": "#FF00FF",
            "road_primary": "#00FFFF",
            "road_secondary": "#39FF14",
            "road_tertiary": "#FFD700",
            "road_residential": "#1A1A3A",
            "road_default": "#141428",
        },
    },
    "pastel": {
        "name": "Pastel",
        "description": "Soft pastel pinks and lavenders",
        "preview_colors": ["#FFF0F5", "#FFB6C1", "#DDA0DD", "#B0E0E6"],
        "render_colors": {
            "bg": "#FFF0F5",
            "text": "#6B4C5A",
            "gradient_color": "#FFF0F5",
            "water": "#D4EAF7",
            "parks": "#D4F0D4",
            "road_motorway": "#E8889A",
            "road_primary": "#DDA0DD",
            "road_secondary": "#D4B8D8",
            "road_tertiary": "#CCB8CC",
            "road_residential": "#D8C8D8",
            "road_default": "#E0D0E0",
        },
    },
    "monochrome": {
        "name": "Monochrome",
        "description": "Timeless black and white with grey tones",
        "preview_colors": ["#FFFFFF", "#000000", "#404040", "#808080"],
        "render_colors": {
            "bg": "#FFFFFF",
            "text": "#111111",
            "gradient_color": "#FFFFFF",
            "water": "#E8E8E8",
            "parks": "#EEEEEE",
            "road_motorway": "#000000",
            "road_primary": "#1A1A1A",
            "road_secondary": "#333333",
            "road_tertiary": "#555555",
            "road_residential": "#888888",
            "road_default": "#AAAAAA",
        },
    },
    "vintage": {
        "name": "Vintage",
        "description": "Aged parchment with warm brown tones",
        "preview_colors": ["#F4E4C1", "#5C4033", "#8B6914", "#CD9B1D"],
        "render_colors": {
            "bg": "#F4E4C1",
            "text": "#3C2A1A",
            "gradient_color": "#F4E4C1",
            "water": "#D4CCA8",
            "parks": "#D8D4A0",
            "road_motorway": "#CD9B1D",
            "road_primary": "#8B6914",
            "road_secondary": "#7A5C30",
            "road_tertiary": "#6A5040",
            "road_residential": "#8B8070",
            "road_default": "#A8A090",
        },
    },
    "arctic": {
        "name": "Arctic",
        "description": "Icy blues and cool steel tones",
        "preview_colors": ["#F0F8FF", "#B0C4DE", "#87CEEB", "#4682B4"],
        "render_colors": {
            "bg": "#F0F8FF",
            "text": "#2C3E50",
            "gradient_color": "#F0F8FF",
            "water": "#D0E8F8",
            "parks": "#D8EAE0",
            "road_motorway": "#4682B4",
            "road_primary": "#5B9BD5",
            "road_secondary": "#7EB3E0",
            "road_tertiary": "#A0C8E8",
            "road_residential": "#B8D4F0",
            "road_default": "#CCE0F5",
        },
    },
    "desert": {
        "name": "Desert",
        "description": "Sandy warmth with terracotta accents",
        "preview_colors": ["#F5DEB3", "#D2691E", "#DEB887", "#CD853F"],
        "render_colors": {
            "bg": "#F5DEB3",
            "text": "#3C2415",
            "gradient_color": "#F5DEB3",
            "water": "#C8D8B8",
            "parks": "#D8D0A0",
            "road_motorway": "#D2691E",
            "road_primary": "#CD853F",
            "road_secondary": "#C4A060",
            "road_tertiary": "#BCA878",
            "road_residential": "#CBB888",
            "road_default": "#D8C8A0",
        },
    },
    "cyberpunk": {
        "name": "Cyberpunk",
        "description": "Futuristic neon pink and cyan on dark violet",
        "preview_colors": ["#0D0221", "#FF2A6D", "#05D9E8", "#D1F7FF"],
        "render_colors": {
            "bg": "#0D0221",
            "text": "#D1F7FF",
            "gradient_color": "#0D0221",
            "water": "#08061A",
            "parks": "#100830",
            "road_motorway": "#FF2A6D",
            "road_primary": "#05D9E8",
            "road_secondary": "#B829DD",
            "road_tertiary": "#7B2D8E",
            "road_residential": "#2A1648",
            "road_default": "#1A0E35",
        },
    },
    "watercolor": {
        "name": "Watercolor",
        "description": "Soft muted greens on linen",
        "preview_colors": ["#FAF0E6", "#6B8E8E", "#9DB5B2", "#C4D7D1"],
        "render_colors": {
            "bg": "#FAF0E6",
            "text": "#3A4A4A",
            "gradient_color": "#FAF0E6",
            "water": "#C8D8D8",
            "parks": "#D0E0D0",
            "road_motorway": "#5A7A7A",
            "road_primary": "#6B8E8E",
            "road_secondary": "#88A8A5",
            "road_tertiary": "#A0BBB8",
            "road_residential": "#B8CCC8",
            "road_default": "#D0DDD8",
        },
    },
    "blueprint": {
        "name": "Blueprint",
        "description": "Technical blue with white line work",
        "preview_colors": ["#003082", "#4A90D9", "#7EC8E3", "#FFFFFF"],
        "render_colors": {
            "bg": "#003082",
            "text": "#FFFFFF",
            "gradient_color": "#003082",
            "water": "#002868",
            "parks": "#003870",
            "road_motorway": "#FFFFFF",
            "road_primary": "#D0E4F8",
            "road_secondary": "#A0C8F0",
            "road_tertiary": "#7EB0E0",
            "road_residential": "#5090D0",
            "road_default": "#3070B0",
        },
    },
    "autumn": {
        "name": "Autumn",
        "description": "Rich fall colors with golden highlights",
        "preview_colors": ["#2D1B00", "#D2691E", "#FF8C00", "#FFD700"],
        "render_colors": {
            "bg": "#2D1B00",
            "text": "#FFE4B5",
            "gradient_color": "#2D1B00",
            "water": "#1A1510",
            "parks": "#2A2010",
            "road_motorway": "#FFD700",
            "road_primary": "#FF8C00",
            "road_secondary": "#D2691E",
            "road_tertiary": "#A0522D",
            "road_residential": "#5A3520",
            "road_default": "#402818",
        },
    },
    "minimal": {
        "name": "Minimal",
        "description": "Subtle greys for an understated look",
        "preview_colors": ["#FAFAFA", "#E0E0E0", "#BDBDBD", "#9E9E9E"],
        "render_colors": {
            "bg": "#FAFAFA",
            "text": "#424242",
            "gradient_color": "#FAFAFA",
            "water": "#ECEFF1",
            "parks": "#F0F0F0",
            "road_motorway": "#757575",
            "road_primary": "#8A8A8A",
            "road_secondary": "#A0A0A0",
            "road_tertiary": "#B8B8B8",
            "road_residential": "#D0D0D0",
            "road_default": "#E0E0E0",
        },
    },
}


def get_theme_colors(theme_id: str) -> List[str]:
    """Return [background, primary_street, secondary_street, accent] for a theme."""
    theme = THEMES.get(theme_id)
    if not theme:
        raise ValueError(f"Unknown theme: {theme_id}")
    return theme["preview_colors"]


def get_render_colors(theme_id: str) -> dict:
    """Return the full 11-key render_colors dict for poster generation."""
    theme = THEMES.get(theme_id)
    if not theme:
        raise ValueError(f"Unknown theme: {theme_id}")
    return theme["render_colors"]
